version: '3.1'
services:
  mongo:
    container_name: ${MONGOHOST}
    image: mongo
    restart: always
    ports:
      - "${MONGOPORT}:27017"
    volumes:
      - ./data:/data/db
      - ./setupDb.js:/docker-entrypoint-initdb.d/setupDb.js:ro
    networks:
      - podcoloursApp
    environment:
      MONGO_INITDB_DATABASE: podcolours
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: pass
  app:
    build: .
    container_name: podApp
    restart: always
    depends_on:
      - mongo
    ports:
      - "80:${APPPORT}"
    networks:
      - podcoloursApp
    environment:
        - APPPORT=${APPPORT}
        - MONGOHOST=${MONGOHOST}
        - MONGOPORT=${MONGOPORT}
        - MONGODATABASE=${MONGODATABASE}
        - SESSIONSECRET=${SESSIONSECRET}
networks:
  podcoloursApp:
    driver: bridge
