print("==== Setting up Database ====");
databaseName = db;

db.dropDatabase();
print(`Created ${databaseName} database`);

db.users.insert({
    name: "Test Not Started",
    department: "Computing",
    university: "Robert Gordon University",
    email: "test@notstarted.com",
    hash: "$2b$10$eTq/E0.UlYj8uyiCfxykTeW5z1n1/yb3pqk8tFqCN8B.TEYwkpqxm",
    test: {
        ts: 1618153071222,
        cards: {
            kept: [],
            discarded: [],
            undecided: [],
            next: {
                id: "Accommodating",
                color: "green",
            },
            complete: false,
        },
        complete: false,
        result: null,
        timeComplete: null,
    },
});

db.users.insert({
    name: "Test Started",
    department: "Computing",
    university: "Robert Gordon University",
    email: "test@started.com",
    hash: "$2b$10$/lJpDONcxv27fYjvkH8ENO8o3JwF481j8TO/B3G1UCr8wGlKTW7fu",
    test: {
        ts: 1618153344550,
        cards: {
            kept: [{ id: "Persuasive", color: "yellow" }],
            discarded: [{ id: "Inquisitive", color: "red" }],
            undecided: [{ id: "Stubborn", color: "green" }],
            next: { id: "Big picture", color: "yellow" },
            complete: false,
        },
        complete: false,
        result: null,
        timeComplete: null,
    },
});

db.users.insert({
    name: "Test In Progress",
    department: "Computing",
    university: "Robert Gordon University",
    email: "test@inprogress.com",
    hash: "$2b$10$zapooDH8Kw08R6ivj5a3ledTkaUwqbx1WqOGSJU3El2IXlsLFombK",
    test: {
        ts: 1618153479012,
        cards: {
            kept: [
                { id: "Persistent", color: "blue" },
                { id: "Forceful", color: "red" },
                { id: "Takes Charge", color: "red" },
                { id: "Accommodating", color: "green" },
                { id: "Prepared", color: "blue" },
                { id: "Fast paced", color: "red" },
                { id: "Analytical", color: "blue" },
                { id: "Enthusiastic", color: "yellow" },
                { id: "Big picture", color: "yellow" },
                { id: "Assertive", color: "red" },
            ],
            discarded: [
                { id: "Easily bored", color: "red" },
                { id: "Accurate", color: "blue" },
                { id: "Kind", color: "green" },
                { id: "Logical", color: "blue" },
                { id: "Attention to Detail", color: "blue" },
                { id: "Harmonious", color: "green" },
                { id: "Task Oriented", color: "blue" },
                { id: "Team Worker", color: "yellow" },
                { id: "Helpful", color: "green" },
                { id: "Imaginative", color: "yellow" },
                { id: "Impatient", color: "red" },
                { id: "Motivated by recognition", color: "yellow" },
                { id: "People Oriented", color: "yellow" },
                { id: "Level Headed", color: "green" },
                { id: "Perfectionist", color: "blue" },
                { id: "Precise", color: "blue" },
                { id: "Friendly", color: "yellow" },
                { id: "Caring", color: "green" },
                { id: "Supportive", color: "green" },
                { id: "Stubborn", color: "green" },
                { id: "Energetic", color: "yellow" },
                { id: "Dependable", color: "green" },
                { id: "Avoids Risk", color: "blue" },
                { id: "Talkative", color: "yellow" },
                { id: "Dislike change", color: "green" },
                { id: "Procrastinates", color: "blue" },
                { id: "Decisive", color: "red" },
                { id: "Sociable", color: "yellow" },
                { id: "Considerate", color: "green" },
                { id: "Focussed", color: "red" },
            ],
            undecided: [],
            next: { id: "Gets results", color: "red" },
            complete: false,
        },
        complete: false,
        result: null,
        timeComplete: null,
    },
});

db.users.insert({
    name: "Test Nearly Complete",
    department: "Computing",
    university: "Robert Gordon University",
    email: "test@nearlycomplete.com",
    hash: "$2b$10$WivgpBtfFv7Hpq0n717sc.8Lh69lTkmLyDa5VxVIaHweVYFSXTNdm",
    test: {
        ts: 1618153611826,
        cards: {
            kept: [
                { id: "Self-Starter", color: "red" },
                { id: "Considerate", color: "green" },
                { id: "Energetic", color: "yellow" },
                { id: "Big picture", color: "yellow" },
                { id: "Influencer", color: "yellow" },
                { id: "Systematic", color: "blue" },
                { id: "Rule Compliant", color: "blue" },
                { id: "Possessive", color: "green" },
                { id: "Deliberate", color: "green" },
                { id: "Good Listener", color: "green" },
                { id: "Logical", color: "blue" },
                { id: "Task Oriented", color: "blue" },
                { id: "Candid", color: "red" },
                { id: "Agreeable", color: "green" },
                { id: "Curious", color: "yellow" },
                { id: "Procrastinates", color: "blue" },
                { id: "Stubborn", color: "green" },
                { id: "Strong Willed", color: "red" },
                { id: "Imaginative", color: "yellow" },
            ],
            discarded: [
                { id: "Adaptable", color: "yellow" },
                { id: "Motivated by recognition", color: "yellow" },
                { id: "Gets results", color: "red" },
                { id: "Fast paced", color: "red" },
                { id: "Decisive", color: "red" },
                { id: "Excitable", color: "yellow" },
                { id: "Reflective", color: "blue" },
                { id: "Sociable", color: "yellow" },
                { id: "Kind", color: "green" },
                { id: "Harmonious", color: "green" },
                { id: "Accurate", color: "blue" },
                { id: "Assertive", color: "red" },
                { id: "Careful", color: "blue" },
                { id: "Direct", color: "red" },
                { id: "Inquisitive", color: "red" },
                { id: "Accommodating", color: "green" },
                { id: "Friendly", color: "yellow" },
                { id: "Supportive", color: "green" },
                { id: "Methodical", color: "green" },
                { id: "People Oriented", color: "yellow" },
                { id: "Collaborative", color: "yellow" },
                { id: "Patient", color: "green" },
                { id: "Attention to Detail", color: "blue" },
                { id: "Takes Charge", color: "red" },
                { id: "Independent", color: "red" },
                { id: "Focussed", color: "red" },
                { id: "Likes Order", color: "blue" },
                { id: "Analytical", color: "blue" },
                { id: "Forward Planning", color: "blue" },
                { id: "Competitive", color: "red" },
                { id: "Forceful", color: "red" },
                { id: "Driving", color: "red" },
                { id: "Networker", color: "yellow" },
                { id: "Talkative", color: "yellow" },
                { id: "Easily bored", color: "red" },
                { id: "Achiever", color: "red" },
                { id: "Persistent", color: "blue" },
                { id: "Dislikes Detail", color: "red" },
                { id: "Prepared", color: "blue" },
                { id: "Avoids Risk", color: "blue" },
                { id: "Calm", color: "green" },
                { id: "Impatient", color: "red" },
                { id: "Loyal", color: "green" },
                { id: "Caring", color: "green" },
                { id: "Optimistic", color: "yellow" },
                { id: "Helpful", color: "green" },
                { id: "Perfectionist", color: "blue" },
                { id: "Animated", color: "yellow" },
                { id: "Spontaneous", color: "yellow" },
                { id: "Work at own pace", color: "green" },
                { id: "Dislike change", color: "green" },
                { id: "Team Worker", color: "yellow" },
                { id: "Systems and Procedures", color: "blue" },
                { id: "Persuasive", color: "yellow" },
                { id: "Impulsive", color: "red" },
                { id: "Dependable", color: "green" },
                { id: "Highly Organised", color: "blue" },
                { id: "Enthusiastic", color: "yellow" },
                { id: "Level Headed", color: "green" },
            ],
            undecided: [{ id: "Precise", color: "blue" }],
            next: { id: "Serious", color: "blue" },
            complete: false,
        },
        complete: false,
        result: null,
        timeComplete: null,
    },
});

db.users.insert({
    name: "Test Complete",
    department: "Computing",
    university: "Robert Gordon University",
    email: "test@complete.com",
    hash: "$2b$10$RcrRadLAAaJMa0VkJRwSR.pMOuaXO.pGiXulTBnrojvfiKD5LFGZ6",
    test: {
        ts: 1618153760017,
        cards: {
            kept: [
                { id: "Self-Starter", color: "red" },
                { id: "Considerate", color: "green" },
                { id: "Energetic", color: "yellow" },
                { id: "Big picture", color: "yellow" },
                { id: "Influencer", color: "yellow" },
                { id: "Systematic", color: "blue" },
                { id: "Rule Compliant", color: "blue" },
                { id: "Possessive", color: "green" },
                { id: "Deliberate", color: "green" },
                { id: "Good Listener", color: "green" },
                { id: "Logical", color: "blue" },
                { id: "Task Oriented", color: "blue" },
                { id: "Candid", color: "red" },
                { id: "Agreeable", color: "green" },
                { id: "Curious", color: "yellow" },
                { id: "Procrastinates", color: "blue" },
                { id: "Stubborn", color: "green" },
                { id: "Strong Willed", color: "red" },
                { id: "Imaginative", color: "yellow" },
                { id: "Precise", color: "blue" },
            ],
            discarded: [
                { id: "Adaptable", color: "yellow" },
                { id: "Motivated by recognition", color: "yellow" },
                { id: "Gets results", color: "red" },
                { id: "Fast paced", color: "red" },
                { id: "Decisive", color: "red" },
                { id: "Excitable", color: "yellow" },
                { id: "Reflective", color: "blue" },
                { id: "Sociable", color: "yellow" },
                { id: "Kind", color: "green" },
                { id: "Harmonious", color: "green" },
                { id: "Accurate", color: "blue" },
                { id: "Assertive", color: "red" },
                { id: "Careful", color: "blue" },
                { id: "Direct", color: "red" },
                { id: "Inquisitive", color: "red" },
                { id: "Accommodating", color: "green" },
                { id: "Friendly", color: "yellow" },
                { id: "Supportive", color: "green" },
                { id: "Methodical", color: "green" },
                { id: "People Oriented", color: "yellow" },
                { id: "Collaborative", color: "yellow" },
                { id: "Patient", color: "green" },
                { id: "Attention to Detail", color: "blue" },
                { id: "Takes Charge", color: "red" },
                { id: "Independent", color: "red" },
                { id: "Focussed", color: "red" },
                { id: "Likes Order", color: "blue" },
                { id: "Analytical", color: "blue" },
                { id: "Forward Planning", color: "blue" },
                { id: "Competitive", color: "red" },
                { id: "Forceful", color: "red" },
                { id: "Driving", color: "red" },
                { id: "Networker", color: "yellow" },
                { id: "Talkative", color: "yellow" },
                { id: "Easily bored", color: "red" },
                { id: "Achiever", color: "red" },
                { id: "Persistent", color: "blue" },
                { id: "Dislikes Detail", color: "red" },
                { id: "Prepared", color: "blue" },
                { id: "Avoids Risk", color: "blue" },
                { id: "Calm", color: "green" },
                { id: "Impatient", color: "red" },
                { id: "Loyal", color: "green" },
                { id: "Caring", color: "green" },
                { id: "Optimistic", color: "yellow" },
                { id: "Helpful", color: "green" },
                { id: "Perfectionist", color: "blue" },
                { id: "Animated", color: "yellow" },
                { id: "Spontaneous", color: "yellow" },
                { id: "Work at own pace", color: "green" },
                { id: "Dislike change", color: "green" },
                { id: "Team Worker", color: "yellow" },
                { id: "Systems and Procedures", color: "blue" },
                { id: "Persuasive", color: "yellow" },
                { id: "Impulsive", color: "red" },
                { id: "Dependable", color: "green" },
                { id: "Highly Organised", color: "blue" },
                { id: "Enthusiastic", color: "yellow" },
                { id: "Level Headed", color: "green" },
                { id: "Serious", color: "blue" },
            ],
            undecided: [],
            next: false,
            complete: true,
            colorCounts: { red: 3, blue: 6, green: 6, yellow: 5 },
        },
        complete: true,
        result: "blue",
        timeComplete: 1618153760017,
    },
});

db.users.insert({
    name: "Test Cards complete no results",
    department: "Computing",
    university: "Robert Gordon University",
    email: "test@cardscompletenoresults.com",
    hash: "$2b$10$XhbcKgtXkYuWU9XA.VqsZeRu2/t8gaMe5JNF77ZXpVlrSHfdL0IGW",
    test: {
        ts: 1618153928665,
        cards: {
            kept: [
                { id: "Assertive", color: "red" },
                { id: "Methodical", color: "green" },
                { id: "Inquisitive", color: "red" },
                { id: "Serious", color: "blue" },
                { id: "Focussed", color: "red" },
                { id: "Friendly", color: "yellow" },
                { id: "Caring", color: "green" },
                { id: "Achiever", color: "red" },
                { id: "Careful", color: "blue" },
                { id: "Forward Planning", color: "blue" },
                { id: "Networker", color: "yellow" },
                { id: "Work at own pace", color: "green" },
                { id: "Procrastinates", color: "blue" },
                { id: "Influencer", color: "yellow" },
                { id: "Systematic", color: "blue" },
                { id: "Enthusiastic", color: "yellow" },
                { id: "Systems and Procedures", color: "blue" },
                { id: "Takes Charge", color: "red" },
                { id: "Perfectionist", color: "blue" },
                { id: "Impatient", color: "red" },
            ],
            discarded: [
                { id: "Rule Compliant", color: "blue" },
                { id: "Dislikes Detail", color: "red" },
                { id: "Spontaneous", color: "yellow" },
                { id: "Animated", color: "yellow" },
                { id: "Stubborn", color: "green" },
                { id: "Considerate", color: "green" },
                { id: "Collaborative", color: "yellow" },
                { id: "Excitable", color: "yellow" },
                { id: "Sociable", color: "yellow" },
                { id: "Decisive", color: "red" },
                { id: "Analytical", color: "blue" },
                { id: "Driving", color: "red" },
                { id: "Curious", color: "yellow" },
                { id: "Agreeable", color: "green" },
                { id: "Good Listener", color: "green" },
                { id: "Loyal", color: "green" },
                { id: "Strong Willed", color: "red" },
                { id: "Independent", color: "red" },
                { id: "Calm", color: "green" },
                { id: "Prepared", color: "blue" },
                { id: "Big picture", color: "yellow" },
                { id: "Harmonious", color: "green" },
                { id: "Fast paced", color: "red" },
                { id: "Easily bored", color: "red" },
                { id: "Talkative", color: "yellow" },
                { id: "Optimistic", color: "yellow" },
                { id: "Precise", color: "blue" },
                { id: "Reflective", color: "blue" },
                { id: "Attention to Detail", color: "blue" },
                { id: "Team Worker", color: "yellow" },
                { id: "Logical", color: "blue" },
                { id: "Motivated by recognition", color: "yellow" },
                { id: "Avoids Risk", color: "blue" },
                { id: "Candid", color: "red" },
                { id: "Likes Order", color: "blue" },
                { id: "Competitive", color: "red" },
                { id: "Impulsive", color: "red" },
                { id: "Dislike change", color: "green" },
                { id: "Deliberate", color: "green" },
                { id: "Persistent", color: "blue" },
                { id: "Self-Starter", color: "red" },
                { id: "Gets results", color: "red" },
                { id: "Adaptable", color: "yellow" },
                { id: "People Oriented", color: "yellow" },
                { id: "Dependable", color: "green" },
                { id: "Helpful", color: "green" },
                { id: "Imaginative", color: "yellow" },
                { id: "Energetic", color: "yellow" },
                { id: "Direct", color: "red" },
                { id: "Persuasive", color: "yellow" },
                { id: "Supportive", color: "green" },
                { id: "Kind", color: "green" },
                { id: "Level Headed", color: "green" },
                { id: "Forceful", color: "red" },
                { id: "Accommodating", color: "green" },
                { id: "Highly Organised", color: "blue" },
                { id: "Patient", color: "green" },
                { id: "Task Oriented", color: "blue" },
                { id: "Accurate", color: "blue" },
                { id: "Possessive", color: "green" },
            ],
            undecided: [],
            next: false,
            complete: true,
        },
        complete: false,
        result: null,
        timeComplete: null,
    },
});

db.content.insert({
    _id: "/",
    content: {
        header: {
            image: "/img/paintSplashLogoTextToRight.png",
        },
        footer: {
            copyright: "© 2021 POD Colours All rights reserved.",
            links: [
                {
                    text: "Home",
                    href: "/",
                },
                {
                    text: "Personality Test",
                    href: "/test",
                },
                {
                    text: "Profile",
                    href: "/profile",
                },
            ],
        },
        hero: {
            title: "Welcome to POD Colours",
            text:
                "POD Colours is a unique personality evaluation test. The POD Colours tool supports individuals and teams to appreciate differences in personality by en-hancing self-awareness, leading to a deeper understanding of oneself and other people. The POD Colours tool is based on psychological research, and provides an indication of your key strengths and potential barriers to success.",
            image: "/img/logo.png",
        },
        redSection: {
            title: "What is POD Colours?",
            text:
                "POD Colours is a tool which supports individuals and teams, helping them to appreciate differences in personality by en-hancing self-awareness, leading to a deeper understanding of oneself and other people.",
        },
        teamPhotoSection: {
            title: "We believe in POD Colours",
            textOne:
                "Understanding the key personality differences between ourselves and the people we interact with helps us to realise how they see us; why they act the way they do; the impact that we have on them and how to get the most out of our interactions by capitalising on strengths.",
            textTwo:
                "The POD Colours tool is based on psychological research, and provide genuine insight into your key areas of strength and potential barriers to success.",
            quoteAuthor: " Tina McGregor, Leadership Development Specialist",
        },
        testimonials: [
            {
                text:
                    "My team have seen amazing results already. Needless to say we are extremely satisfied",
                name: "Jody Heath",
            },
            {
                text:
                    "I love how extensive the profile is! It will really help me understand myself better.",
                name: "Ariya Sanders",
            },
            {
                text: "Genuinely insightful and an interesting read.",
                name: "Jim Millar",
            },
            {
                text: "A profound assessment of my personality.",
                name: "Tony Crouch",
            },
            {
                text: "More accurate than I could have hoped for",
                name: "Jana Holder",
            },
        ],
        callToAction: {
            title: "Ready to get started?",
            text:
                "We'll guide you every step of the way towards your self improvement.",
        },
    },
});

print("==== Database Setup Complete ====\n\n");
